name = "gsmp5"
author = "DrTheo_, Kalipico"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0dd5e2fbcaef3a4c71fb3ebb4bad79bcac0844c79383a1fb258d6f1b789d0fe"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
