name = "gsmp5"
author = "DrTheo_, Kalipico"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5d02b530ff045ae0c3902e1bbec0678531407999f7cb7c42670d60b0cca28de"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
