name = "gsmp5"
author = "DrTheo_, Kalipico"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1da085944e586b9bd7748e742d418050319de6813d3cfa7be02f1432849abf86"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
