#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Sun Apr 27 17:05:17 PDT 2025
alwaysLogTamperWarnings=true
